import fs from "fs";
import path from "path";
import { glob } from "glob";
import { RULES_DIR, AGENTS_MD_PATH, METADATA_PATH } from "./config";
import { parseRuleFile } from "./parser";
import { SkillMetadata } from "./types";

/**
 * Build the compiled AGENTS.md from all rule files.
 */
async function build(): Promise<void> {
  console.log("Building AGENTS.md...");

  // Load metadata
  const metadata: SkillMetadata = JSON.parse(
    fs.readFileSync(METADATA_PATH, "utf-8")
  );

  // Find all rule files (exclude _ prefixed files)
  const ruleFiles = await glob("*.md", {
    cwd: RULES_DIR,
    ignore: ["_*.md"],
    absolute: true,
  });

  ruleFiles.sort();

  // Parse all rules
  const rules = ruleFiles
    .map((f) => parseRuleFile(f))
    .filter((r) => r !== null);

  // Generate output
  const lines: string[] = [
    "<!-- AUTO-GENERATED FILE — DO NOT EDIT MANUALLY -->",
    "<!-- Generated by packages/doris-best-practices-build -->",
    `<!-- Generated on ${new Date().toISOString()} -->`,
    "",
    `# Doris Best Practices — Compiled Rules (v${metadata.version})`,
    "",
    metadata.abstract,
    "",
  ];

  if (rules.length === 0) {
    lines.push(
      "> **Note:** No rules have been compiled yet. Add rule files to `rules/` and run",
      "> `npm run build` in `packages/doris-best-practices-build/` to regenerate this document.",
    );
  } else {
    // Group rules by section
    const sections = new Map<string, typeof rules>();
    for (const rule of rules) {
      const group = sections.get(rule.section) || [];
      group.push(rule);
      sections.set(rule.section, group);
    }

    for (const [section, sectionRules] of sections) {
      lines.push(`## ${section}`);
      lines.push("");
      for (const rule of sectionRules) {
        lines.push(`### ${rule.frontmatter.title}`);
        lines.push("");
        lines.push(
          `**Impact:** ${rule.frontmatter.impact} — ${rule.frontmatter.impactDescription}`
        );
        lines.push(`**Tags:** ${rule.frontmatter.tags.join(", ")}`);
        lines.push("");
        lines.push(rule.content);
        lines.push("");
        lines.push("---");
        lines.push("");
      }
    }
  }

  fs.writeFileSync(AGENTS_MD_PATH, lines.join("\n"), "utf-8");
  console.log(
    `Done. Compiled ${rules.length} rules into ${path.relative(process.cwd(), AGENTS_MD_PATH)}`
  );
}

build().catch((err) => {
  console.error("Build failed:", err);
  process.exit(1);
});
